### ISSUE TITLE
Cannot activate any virtualenvs on OS X 10.11.2 after upgrade to 20151222

### ISSUE THREAD

**Issue by ad-lebedev** [yyuu/pyenv-virtualenv#137] opened 2015-12-29 15:35 UTC
Hi!
After upgrade to pyenv-virtualenv-20151222 and pyenv-20151222 I cannot see any python libraries in the virtualenvs. In every directory linked to the virtualenvs, ```pip freeze``` shows me only system libraries.
Both packages have been installed with homebrew.
On the other hand, I see all libraries from PyCharm package manager, but PyCharm looks directly to the ~/.pyenv/versions/....

**Comment by ad-lebedev** [comment] 2015-12-29 20:17
On version 20151103 everything is fine

**Comment by yyuu** [comment] 2015-12-29 22:12
It sounds 'pyenv local' isn't working properly by unknown reason. Please check the output of 'pyenv versions' if the virtualenv is properly selected

**Comment by ad-lebedev** [comment] 2015-12-30 08:26
this is my ```pyenv versions```:
```bash
╭─ad@adBook  ~
╰─$ pyenv versions                                                                                                                                                                                                                                                                1 ↵
* system (set by ...../.pyenv/version)
  3.4.2
  ...
  portal-2.7.10
  ...
```
when I'm going to directory linked to the, for example, ```portal-2.7.10```, I see this message:
```bash
pyenv-virtualenv: deactivate
pyenv-virtualenv: activate portal-2.7.10
╭─ad@adBook  ~portal  ‹master›
╰─$
```
here is the ```.python-version``` file content:
```bash
╭─ad@adBook  ~portal  ‹master›
╰─$ cat .python-version
portal-2.7.10
```
```pyenv versions``` output in this directory is:
```bash
╭─ad@adBook  ~portal  ‹master›
╰─$ pyenv versions
  system
  3.4.2
  ...
* portal-2.7.10 (set by ...../.python-version)
  ...
```
but ```pip freeze``` returns me only system python libraries.
If I switch back to the 20151103 version of pyenv-virtualenv, everything works correctly

**Comment by dan-blanchard** [comment] 2016-01-06 14:06
I'm experiencing a similar problem where pip can't see any of the packages in my conda environment, but conda can.

**Comment by jimmywan** [comment] 2016-01-12 18:34
> I'm experiencing a similar problem where pip can't see any of the packages in my conda environment, but conda can.

Unrelated to OP since it wasn't on a Mac, but I had this problem when I wasn't using a pip that was from my virtualenv. Do a `pyenv which pip` and make sure you're using the right pip.

**Comment by artlogic** [comment] 2016-01-15 22:13
I'm experiencing the same problem, but on Mac OS 10.9.5. I haven't invested fully, but it's clear the virtualenv isn't being added to sys.path.

**Comment by artlogic** [comment] 2016-01-16 05:04
I've just upgraded to pyenv-virtualenv 20160112 and the problem persists.

**Comment by artlogic** [comment] 2016-01-16 17:22
I can confirm that 20151222 seems to be the breaking release. 20151103 is working fine with the latest pyenv (20151222) on my system.

**Comment by artlogic** [comment] 2016-01-17 01:39
I have found my problem - it was due to a custom configuration needed for wxPython. It appears to be related to pyenv-virtualenv not using the bin/activate script anymore. I'm looking for solutions, but I wouldn't call this a bug in pyenv-virtualenv (in my case).

**Comment by yyuu** [comment] 2016-05-20 00:31
I'll close this for now. Please let me know if there's something need to be fixed.

**Closed by yyuu** 2016-05-20 00:31 UTC
